[package]
name = "realpath"
version = "0.1.0"
edition = "2018"

authors = ["cptpcrd"]

[features]
default = ["std"]

std = []

[dependencies]
libc = { version = "0.2", default-features = false }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
